version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: damnvulnerablesqli
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: ['--default-authentication-plugin=mysql_native_password']
    networks:
      - sqli-net

  web:
    image: php:7.4-apache
    volumes:
      - ./web:/var/www/html
    environment:
      MYSQL_ROOT_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: damnvulnerablesqli
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - sqli-net

networks:
  sqli-net:
    driver: bridge

